import type { Metadata } from "next";
import { Geist, Geist_Mono, Funnel_Sans, Electrolize} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import Container from "@/components/container";
import { ThemeProvider } from "@/providers/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const electrolize = Electrolize({
  variable: "--font-electrolize",
  subsets: ["latin"],
  weight: "400",
});

const funnelSans = Funnel_Sans({
  variable: "--font-funnel-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const BackgroundPattern = () =>{
  return(
  <div
    className="absolute inset-0 z-0"
    style={{
      backgroundImage: `
        linear-gradient(to right, #e7e5e4 1px, transparent 1px),
        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px),
        dark:linear-gradient(to right, #adb5bd 1px, transparent 1px),
        dark:linear-gradient(to bottom, #adb5bd 1px, transparent 1px)
      `,
      backgroundSize: "20px 20px",
      backgroundPosition: "0 0, 0 0",
      maskImage: `
        repeating-linear-gradient(
              to right,
              black 0px,
              black 3px,
              transparent 1px,
              transparent 8px
              dark:repeating-linear-gradient(to right, #adb5bd 0px, #adb5bd 3px, transparent 1px, transparent 8px),
            ),
            repeating-linear-gradient(
              to bottom,
              black 0px,
              black 3px,
              transparent 3px,
              transparent 8px
              dark:repeating-linear-gradient(to bottom, #adb5bd 0px, #adb5bd 3px, transparent 3px, transparent 8px),
            ),
            radial-gradient(ellipse 100% 100% at 100% 90%, #000 98%, transparent 90%),
            dark:radial-gradient(ellipse 100% 100% at 100% 90%, #adb5bd 98%, transparent 90%)
      `,
      WebkitMaskImage: `
 repeating-linear-gradient(
              to right,
              black 0px,
              black 3px,
              transparent 3px,
              transparent 8px
              dark:repeating-linear-gradient(to right, #adb5bd 0px, #adb5bd 3px, transparent 1px, transparent 8px),
            ),
            repeating-linear-gradient(
              to bottom,
              black 0px,
              black 3px,
              transparent 3px,
              transparent 8px
              dark:repeating-linear-gradient(to bottom, #adb5bd 0px, #adb5bd 3px, transparent 3px, transparent 8px),
            ),
            radial-gradient(ellipse 100% 100% at 50% 100%, #000 90%, transparent 100%)
      `,
      maskComposite: "intersect",
      WebkitMaskComposite: "source-in",
    }}
  />
  )
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${electrolize.variable} ${funnelSans.variable} antialiased relative`}
        suppressHydrationWarning
      >
        <ThemeProvider attribute='class' defaultTheme="system" enableSystem disableTransitionOnChange>
          <BackgroundPattern />
          <Container>
            <Navbar />
            {children}  
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
